name: CI/CD dev
on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ "test" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: deploy to Server
        run: |
          docker stop odoo16e-test_db_1 odoo16e-test_webs_1
          cd /opt/odoo16e-test
          docker-compose up -d
